export const FETCH_GET_GENRS_PENDING = 'FETCH_GET_GENRS_PENDING';
export const FETCH_GET_GENRS_SUCCESS = 'FETCH_GET_GENRS_SUCCESS';
export const FETCH_GET_GENRS_ERROR = 'FETCH_GET_GENRS_ERROR';
// @TODO: ADD ANOTHER ACTIONS WHEN FIX REDUX ISSUE